/*SCHEMMA*/
/*DROP*/
DROP SCHEMA IF EXISTS BESTSELLER;

/*CREATE*/
CREATE SCHEMA BESTSELLER;

/*DDL*/
/*DROP*/
DROP TABLE IF EXISTS BESTSELLER.LISTADESEJO;
DROP TABLE IF EXISTS BESTSELLER.LIVRO;
DROP TABLE IF EXISTS BESTSELLER.USUARIO;
DROP TABLE IF EXISTS BESTSELLER.CATEGORIA;
DROP TABLE IF EXISTS BESTSELLER.AUTOR;
DROP TABLE IF EXISTS BESTSELLER.EDITORA;

/*CREATE*/
CREATE TABLE BESTSELLER.USUARIO (
	ID INT(6) auto_increment PRIMARY KEY,
    NM_USUARIO VARCHAR(100) NOT NULL,
    CD_LOGIN VARCHAR(100) NOT NULL,
    CD_SENHA VARCHAR(100) NOT NULL,
    IS_ADMIN VARCHAR(1) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE BESTSELLER.CATEGORIA(
	ID INT(6) auto_increment PRIMARY KEY,
    NM_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE BESTSELLER.AUTOR(
	ID INT(6) auto_increment PRIMARY KEY,
    NM_AUTOR VARCHAR(100) NOT NULL,
	NM_IDIOMA VARCHAR(100) NOT NULL,
    NM_GENERO VARCHAR(100) NOT NULL,
    NM_PAISORIGEM VARCHAR(100) NOT NULL,
    DT_NASCIMENTO VARCHAR(10) NOT NULL,
    QT_OBRAS INT(100) NOT NULL,
    NL_ESCOLAR VARCHAR(100) NOT NULL,
    NM_ENDERECO VARCHAR(100) NOT NULL,
    DT_FALECIMENTO VARCHAR(10),
	NM_PREMIOS VARCHAR(100)
);

CREATE TABLE BESTSELLER.EDITORA(
	ID INT(6) auto_increment PRIMARY KEY,
	NM_NOME VARCHAR(100) NOT NULL,
    TP_TIPO VARCHAR(100) NOT NULL,
    NM_GENERO VARCHAR(100) NOT NULL,
    DT_FUNDACAO VARCHAR(10) NOT NULL,
    NM_SEDE VARCHAR(100) NOT NULL,
    NM_PROPRIETARIO VARCHAR(100) NOT NULL,
    NM_PRODUTOS VARCHAR(100) NOT NULL,
	SITE_OFICIAL VARCHAR(100) NOT NULL,
	NM_CONTATO VARCHAR(100) NOT NULL,
    VL_FATURAMENTO DOUBLE(40,20),
    NM_PESSOAS_CHAVE VARCHAR(500)
);

CREATE TABLE BESTSELLER.LIVRO(
	ID INT(6) auto_increment PRIMARY KEY,
    NM_TITULO VARCHAR(100) NOT NULL,
    CD_ISBN VARCHAR(100) NOT NULL,
    CD_EDICAO VARCHAR(100) NOT NULL,
    QT_VOLUME VARCHAR(100) NOT NULL,
    DT_PUBLICACAO VARCHAR(10) NOT NULL,
    NM_LOCAL_PUBLICAO VARCHAR(100) NOT NULL,
	IDADE_RECOMENDADA INT(3) NOT NULL,
	ID_CAPA VARCHAR(50) NOT NULL,
	DS_DESCRICAO VARCHAR(100) NOT NULL,
	VL_PRECO DOUBLE(40,20) NOT NULL,
    FK_AUTOR INT(6),
    FK_EDITORA INT(6),
    FK_CATEGORIA INT(6),
    FOREIGN KEY (FK_AUTOR) REFERENCES AUTOR(ID) ON DELETE CASCADE,    
    FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(ID) ON DELETE CASCADE,    
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE    
);

CREATE TABLE BESTSELLER.LISTADESEJO (	
    FK_LIVRO INT(6),
    FK_USUARIO INT(6),
    FOREIGN KEY (FK_LIVRO) REFERENCES LIVRO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    PRIMARY KEY(FK_LIVRO, FK_USUARIO)
);

/*DML*/
INSERT INTO BESTSELLER.USUARIO (NM_USUARIO, CD_LOGIN, CD_SENHA, IS_ADMIN,EMAIL) VALUES ('Victor Monte', 'admin', 'admin', 'S','victorbcm@hotmail.com');